### ISSUE TITLE
Missing PrepFEM2.m file

### ISSUE THREAD

**Issue by joaofonseca9** [JiamingCao/NIRS-EEG#1]
First of all, congratulations on the amazing article and thank you for making the code available.
I'm quite interested in combined EEG/fNIRS as it is my internship goal. I was trying to run your code after some analysis and realized that a PrepFEM2.m file that is referred on the README and is used for the forward model generation is not in the GitHub. Is there a way you could make it available?

Best regards,

João Fonseca

**Comment by JiamingCao** [comment]
Thanks for your interest in my work! Somehow I was careless enough to have forgotten to add the file. Now it's been added. Let me know if you run into any other issues.
I'm also happy to share the calculated models as .mat files if you'd like. I'm unable to upload to Github due to the file size limit.

**Comment by joaofonseca9** [comment]
Dear,

Thank you for such a fast reply. I would be grateful if you could share the .mat files.
As a matter of fact, I sent an email a few days ago to Dr. Theodore Huppert regarding my interest in the paper. I’m an MSc student and I will be working with a new EEG/fNIRS combined cap produced by Artinis and my internship goal is to find a way to integrate the two signals
My idea was to adapt the code for the article so that it could take in actual data I will acquire in the next month or two. Since the article mentions you used simulated data, I thought it would be interesting to test your model with actual data. I’m not quite sure if that is feasible in my 4 months of internship but I will try my best.
Once again, thank you for your help,

Best regards,

João Fonseca




De: JiamingCao<mailto:notifications@github.com>
Enviado: 9 de março de 2021 06:42
Para: JiamingCao/NIRS-EEG<mailto:NIRS-EEG@noreply.github.com>
Cc: joaofonseca9<mailto:joaopbf9@hotmail.com>; Author<mailto:author@noreply.github.com>
Assunto: Re: [JiamingCao/NIRS-EEG] Missing PrepFEM2.m file (#1)


Thanks for your interest in my work! Somehow I was careless enough to have forgotten to add the file. Now it's been added. Let me know if you run into any other issues.
I'm also happy to share the calculated models as .mat files if you'd like. I'm unable to upload to Github due to the file size limit.
